
services:
  db:
    image: postgres:15
    container_name: ia-db
    restart: always
    environment:
      POSTGRES_USER: iacapital
      POSTGRES_PASSWORD: supersegura
      POSTGRES_DB: iacapital_db
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama:latest
    container_name: ia-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: ia-gotenberg
    restart: always
    # We expose port 3000. 
    # Left side is your PC/Server port, Right side is container port.
    ports:
      - "3080:3080"
    # Command arguments (Optional): 
    # These are defaults, but good to know if you need to increase timeout for big PDFs
    command:
      - "gotenberg"
      - "--api-port=3080"
      - "--api-timeout=30s"

  backend:
    build:
      context: ./backend
    container_name: ia-backend
    restart: always
    # working_dir removed for production
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
      - ./uploads:/app/uploads
      - /Users/javiersantana/Desktop/ia-reports:/app/reports

    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: iacapital
      DB_PASSWORD: supersegura
      DB_NAME: iacapital_db
      JWT_SECRET: supersecret_en_env
      OLLAMA_HOST: http://ollama:11434
      OLLAMA_MODEL: llama3.1:8b-instruct-q4_K_M
      AI_MAX_TOKENS: "512"
      AI_TEMPERATURE: "0.5"
    depends_on:
      - db
      - ollama
    command: ["npm", "run", "start:dev"]
    ports:
      - "5001:5000"

  frontend:
    build:
      context: ./frontend
    container_name: ia-frontend
    restart: always
    working_dir: /app
    volumes:
      - ./frontend:/app
      # - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: /api
      NEXT_API_PROXY_ORIGIN: http://backend:5000
      NODE_ENV: development
    depends_on:
      - backend
    ports:
      - "3000:3000"
    command: sh -c "npm ci && npm run dev"
    # command: npm run dev
